Server Settings:
  Server: example.tld
  Port: 5222
  Username: username
  Password: password
  Room: notifications@example.tld
  Nickname: testbot

Bot Settings:
  Listen Time: 30

Logging Settings:
  #Master switch
  Enabled: True
  #CRITICAL, ERROR, WARNING, INFO, DEBUG
  Level: DEBUG
  Log to Console: True
  Log to File: True
  Logfile: xmpp_bot.log
